**************************************
*      Model Generated by MODPEX     *
*Copyright(c) Symmetry Design Systems*
*         All Rights Reserved        *
*    UNPUBLISHED LICENSED SOFTWARE   *
*   Contains Proprietary Information *
*      Which is The Property of      *
*     SYMMETRY OR ITS LICENSORS      *
*    Modeling services provided by   *
* Interface Technologies www.i-t.com *
**************************************
.MODEL MUR160 D
+IS=2.09761e-09 RS=0.102264 N=1.73768 EG=1.30748
+XTI=0.5 BV=600 IBV=5e-06 CJO=2.04093e-11
+VJ=1.5 M=0.660816 FC=0.5 TT=1.04325e-07
+KF=0 AF=1
* Model generated on October 8, 2003
* Model format: PSpice
